### ISSUE TITLE
No math functions and algorithms present yet along with several other algorithms

### ISSUE THREAD

**Issue by Jetas18** [digitallyamar/Algorithms#3]
Assign me the task to implement Basic math functions in C and python. I will also implement other several algorithms such as for binary searching, hashing, etc.... Would be really helpful to both of us :DD

**Comment by digitallyamar** [comment]
> Assign me the task to implement Basic math functions in C and python. I will also implement other several algorithms such as for binary searching, hashing, etc.... Would be really helpful to both of us :DD

``` [tasklist]
### Implement basic math functions using C & Python by creating a new folder called **math** under existing **lib** directory - Assigning the implementation to @Jetas18 

```
